### ISSUE TITLE
Unable to use couchdb-push with basic authentication url's

### ISSUE THREAD

**Issue by pradeep122** [jo/couchdb-push#10]
Whenever I use couchdb-push for a url with basic auth , I get an ```ENOENT``` error

```
$>> couchdb-push http://admin:password@localhost:5984/pop --index

	{ [Error: ENOENT, stat '/home/deepster/POP/couchdb/http:/admin:password@localhost:5984/pop']
	  errno: 34,
	  code: 'ENOENT',
	  path: '/home/deepster/POP/couchdb/http:/admin:password@localhost:5984/pop' }

```

When I use couchdb-push on a fresh couchdb installation, without any admins setup, It works fine

**Comment by jo** [comment]
Thanks for reporting!

There was an error in commandline argument processing which I just fixed in `2.0.4`. Should work now.
