### ISSUE TITLE
Handle database names with `/` in them

### ISSUE THREAD

**Issue by BigBlueHat** [jo/couchdb-push#13]
Right now, if I give couchdb-push an URL like `http://localhost:5984/mail/bigbluehat-com/byoung` it throws the following error:

```
...\node_modules\couchdb-push\node_modules\couchdb-ensure\index.js:12
  couch.request({
        ^
TypeError: undefined is not a function
```

If I escape them, however, things work as they should: `http://localhost:5984/mail%2Fbigbluehat-com%2Fbyoung`

Obviously the escaped version is what CouchDB actually wants, but it'd be nice for the developer to not have to care that much--or go figure out what's needed from that error.

Having this as part of the library would save a bunch of URL parsing boilerplate in other people's code too, fwiw.

Thanks!

**Comment by jo** [comment]
The url id directly passed to [nano](https://github.com/dscape/nano). Do you think also nano would benefit from this enhancement?

**Comment by BigBlueHat** [comment]
Ah. Good to know. nano could *definitely* use this feature.

Should I post the issue in Jira--now that nano's at the ASF? Or do you just want to fix it 'cause your awesome and stuff? :smile_cat:

**Comment by jo** [comment]
Could you please open an issue on dscape/nano?

**Comment by jo** [comment]
I currently work on that repo and push also to Apache/couchdb-nano to keep it in sync in the meantime until the move is complete.

**Comment by BigBlueHat** [comment]
On it. I'll close this one in favor of it being fixed there. Thanks @jo!
