### ISSUE TITLE
Beginner issue

### ISSUE THREAD

**Issue by broerse** [jo/couchdb-push#26]
Hi,

I like to use your module for my ember-cli-deploy-couchdb and it works on my localhost but I have some async issue. In

https://github.com/broerse/ember-cli-deploy-couchdb/blob/master/index.js

the couchapp is never upload to cloudant because the deploy does not wait for the push. The this.log is never printed. On localhost it is faster and than it works.

How do I wait? I am new to nodejs so I hope you can give me some pointers.

**Comment by jo** [comment]
Hi @broerse, welcome to nodejs!

You can use [async](https://github.com/caolan/async), which 

> provides straight-forward, powerful functions for working with asynchronous JavaScript.

With [`async.each()`](https://github.com/caolan/async#each) (to handle the upload in paralell) or `async.eachSeries()` (to push one file after the other) `callback` is called when all files have been processed:

```diff
- distFiles.forEach(function (item) {
+ async.eachSeries(distFiles, function (item) {
//
+}, callback)
```

**Comment by broerse** [comment]
Thanks but the problem seems to be that push is stopped because the script ends. Just tried RSVP but it does not help yet. It also does not wait?

```
      upload: function(/* context */) {
        var couchDir    = this.readConfig('couchDir');
        var db          = this.readConfig('db');
        var promise = new Promise(function(resolve, reject) {
          push(db, couchDir, function(error, response) {
            if(error) {
              reject(response);
            } else {
              resolve('Upload OK');
            }
          });
        });
        promise.then(function(value) {
          // on fulfillment
          console.log(value);
        }, function(reason) {
          // on rejection
          console.log(value);
        });
        console.log('zzzz');
      },
```

**Comment by jo** [comment]
Have you tried to return the promise from the upload function?

**Comment by broerse** [comment]
Yes I see the `distFiles.forEach` is wrong. Thanks. I will test if it is the problem I have.

**Comment by jo** [comment]
No, I think I was wrong - I overread that `didBuild` is sync because you used `writeFileSync`. You maybe need to return a Promise from the `upload` function like you wrote in the comment above.

**Comment by broerse** [comment]
That was it:

```javascript
      upload: function(/* context */) {
        var couchDir    = this.readConfig('couchDir');
        var db          = this.readConfig('db');
        var promise = new Promise(function(resolve, reject) {
          push(db, couchDir, function(error, response) {
            if(error) {
              console.log('Error');
              reject(response);
            } else {
              console.log('Upload OK');
              resolve('Upload OK');
            }
          });
        });
        console.log('Start Upload');
        return promise;
      },
```

Many Thanks!!!

Just deployed: [https://martinic.cloudant.com/emberapp/_design/deploytest1/_rewrite/](https://martinic.cloudant.com/emberapp/_design/deploytest1/_rewrite/)
